[package]
name = "reddit2lemmy"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
gumdrop = "0.8.1"
log = "0.4.27"
postgres = "0.19.10"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
walkdir = "2.5.0"
